version: '3.6'
services:
  db:
    image: mysql:5.7
    restart: unless-stopped
    container_name: db
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci
    ports:
      - "127.0.0.1:3356:3306"
    env_file:
      - ./conf/mysql.env
  adminer:
    image: adminer
    restart: always
    container_name: adminer
    ports:
      - "8080:8080"
    depends_on:
    - db
  web:
    build: .
    image: web
    container_name: web
    command: ["./wait-for", "db:3306", "--",  "pm2-runtime", "start", "./ecosystem.config.js", "--env", "production" ]
    env_file:
      - ./conf/web.env
    ports:
     - "3333:3333"
    depends_on:
    - db
  migration:
    image: web
    container_name: migration
    command: ["./wait-for", "db:3306", "--", "./migration.sh"]
    depends_on:
    - db
    - web